const PARTICLE_SIZE = 30;

const CONSTANTS = {
    PARTICLE_SIZE: PARTICLE_SIZE,
    PARTICLE_FALL_SPEED: 1,
    PARTICLE_COLOUR: "white",
    WORLD_SPEED: 3,
    CANVAS_WIDTH: 500,
    CANVAS_HEIGHT: 500,
    CANVAS_BORDER_OFFEST: 6 + PARTICLE_SIZE
}

module.exports = CONSTANTS;